package com.quishguard.sentinel.entity;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;

@Entity
@Table(name = "url_analysis_cache")
@Getter
@Setter
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class UrlAnalysisCache {

    // PK is SHA-256 hash of the URL — not a UUID
    // Generated by our code, not by Hibernate
    @Id
    @Column(name = "url_hash", length = 64)
    private String urlHash;

    @Column(columnDefinition = "TEXT")
    private String url;

    // Full VirusTotal API response stored as JSONB
    // JsonNode handles arbitrary JSON without double-encoding
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "vt_result", columnDefinition = "jsonb")
    private JsonNode vtResult;

    // Full Google Safe Browsing API response stored as JSONB
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "gsb_result", columnDefinition = "jsonb")
    private JsonNode gsbResult;

    @Column(name = "cached_at")
    private Instant cachedAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @PrePersist
    public void prePersist() {
        this.cachedAt = Instant.now();
    }
}